version: '3'
services:
  raspio:
    image: cecchisandrone/raspio:latest    
    devices:
    - "/dev/gpiomem:/dev/gpiomem"
    ports:
    - 6000:6000
    restart: always
    volumes:
    - /home/pi/config.ini:/app/config.ini
