version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202111-01
    resource_class: arm.medium
    steps:
      - checkout
      - run: |
          # ARM build
          docker run --rm --privileged multiarch/qemu-user-static:register --reset 
          docker build -t cecchisandrone/raspio:latest . 
          docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD
          docker push cecchisandrone/raspio:latest
  deploy:
    machine:
      image: ubuntu-2004:202111-01
    resource_class: arm.medium
    steps:
      - run:
          command: ssh -o StrictHostKeyChecking=no -l pi $SMARTHOME_SSH_HOST -p $SMARTHOME_SSH_PORT "docker pull cecchisandrone/raspio && docker rm -f raspio || true &&  docker run --name raspio -v /home/pi/config.ini:/app/config.ini -p 6000:6000 --device /dev/gpiomem --restart always -d cecchisandrone/raspio"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
