version: 2
jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
          docker build -t repo.treescale.com/cecchisandrone/raspio:latest . 
          docker login repo.treescale.com -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD
          docker push repo.treescale.com/cecchisandrone/raspio:latest
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          command: ssh -o StrictHostKeyChecking=no -l pi $SMARTHOME_SSH_HOST -p $SMARTHOME_SSH_PORT "docker pull repo.treescale.com/cecchisandrone/raspio && docker rm -f raspio || true &&  docker run --name raspio -v /home/pi/config.ini:/data/config.ini -p 6000:6000 -d repo.treescale.com/cecchisandrone/raspio"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
